{
  "hash": "57090ed236f7d195d88e53d69245b75c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Ten -- Point Estimation # Title of the document\n\n# Bibliography Details\nbibliography: Lab10References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab10WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n\n# Lab 8 Notes\n\n##  Altham's Multiplicative Binomial Distribution\n\nThe PMF for Altham's Multiplicative Binomial Distribution is\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}.$$ \nJust so we start on the same page, I have included my `R` function for computing probability using this distribution.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbinom <- function(x, size, prob, theta){\n  normalizing.constant <- 0\n  for(j in 0:size){\n    normalizing.constant <- normalizing.constant + \n      choose(size, j) * prob^j * (1-prob)^(size-j) * theta^(j*(size-j))\n  }\n  # Probability Mass at x=x\n  (1/normalizing.constant) *\n    choose(size, x) * prob^x * (1-prob)^(size-x) * theta^(x*(size-x)) *\n      (x>=0)*(x<=size)\n}\n```\n:::\n\n\n \\normalsize\n\n# Altham's Multiplicative Beta Binomial Distribution\nThe PMF for Altham's Multiplicative Beta Binomial Distribution is\n$$f_X(x) = \\left[\\int_{0}^1 \\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right) dp\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\nJust so we start on the same page, I have included my `R` function for computing probability using this distribution.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbbinom.single <- function(x, size, alpha, beta, theta){\n    integrand <- function(p) {\n    sapply(p, # integrate will pass in a vector, so we use sapply to apply the following\n           function(p_val){\n             # f(x|p) * f(p|alpha, beta)\n             daltbinom(x, size, p_val, theta) * dbeta(p_val, alpha, beta)\n           }\n    )\n  }\n  # Probability Mass at x=x\n  # integrate(integrand, lower = 0, upper = 1)$value * (x>=0)*(x<=size)\n  # I shrink the bounds below to avoid log(0)=-infinty\n  # I use try() to catch when there is an error and avoid crashing\n  res <- try(integrate(integrand, lower = 1e-7, upper = 1 - 1e-7)$value * \n                  (x>=0)*(x<=size), \n             silent = TRUE)\n  # If there is an error, return a near-zero probability\n  if(inherits(res, \"try-error\")) return(0.1^6)\n  \n  res\n}\n# Write a function that works on a vector\ndaltbbinom <- function(x, size, alpha, beta, theta){\n  sapply(X=x, FUN=daltbbinom.single, size=size, alpha=alpha, beta=beta, theta=theta)\n}\n```\n:::\n\n\n \\normalsize\n\n# Question 1\n\nIn Lab 8, we use Altham's Multiplicative Binomial Distribution. Your job was to interpret the impact of $\\theta$ in that equation. In this lab, we will model the number of legs won in a best of eleven (first to six) match. \n\nTo help us think about the interpretation, something that was challenging before, let's try something a little more manageable.\n\n## Part a\nSuppose a player has a 50\\% chance of winning a specific leg, that is let $p=0.50$. Let's look at the probability they win ($x=6$) legs in the match. Compute this probability over a sequence from $\\theta=0.5$ to $\\theta=1.5$ and plot it using a line where the $x$-axis is $\\theta$ and the $y$-axis is $P(X=6)$.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#sequence of thetas\ntheta_seq <- seq(0.5, 1.5, length.out = 1000)\n\n# probability of 6 wins\nprob6 = daltbinom(6, 11, 0.5, theta_seq)\n\nggdat = tibble(theta = theta_seq, prob = prob6)\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(ggdat, aes(x = theta, y = prob)) +\n  geom_line() +\n  xlab(expression(theta)) +\n  ylab(\"P(X = 6)\") +\n  ggtitle(\"P(X = 6) vs. theta\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Altham's Binomial](Lab10WriteUp_files/figure-pdf/theta.5_1.5-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## Part b\nNow, plot Altham's Multiplicative Binomial Distribution under the same parameters with $\\theta=0.50$, $\\theta=1$, and $\\theta=1.5$. Use `ncol=1` in `facet_wrap()` to plot the PMFs in a single column for comparing.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# prob for thetas\ntheta0.5 = daltbinom(6, 11, 0.5, 0.5)\ntheta1 = daltbinom(6, 11, 0.5, 1)\ntheta1.5 = daltbinom(6, 11, 0.5, 1.5)\n\nggdat = tibble(x = 0:11) |>\n  mutate(theta0.5 = daltbinom(x, 11, 0.5, 0.50),\n         theta1 = daltbinom(x, 11, 0.5, 1.00),\n         theta1.5 = daltbinom(x, 11, 0.5, 1.50))\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nplot1 = ggplot() +\n  geom_linerange(data = ggdat, aes(x = x, ymin = 0, ymax = theta0.5)) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:11) +\n  ylab(\"Probability\") +\n  ggtitle(\"theta = 0.50\") +\n  theme_bw()\n\nplot2 = ggplot() +\n  geom_linerange(data = ggdat, aes(x = x, ymin = 0, ymax = theta1)) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:11) +\n  ylab(\"Probability\") +\n  ggtitle(\"theta = 1.00\") +\n  theme_bw()\n\nplot3 = ggplot() +\n  geom_linerange(data = ggdat, aes(x = x, ymin = 0, ymax = theta1.5)) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks = 0:11) +\n  ylab(\"Probability\") +\n  ggtitle(\"theta = 1.50\") +\n  theme_bw()\n\nplot1 / plot2 / plot3\n```\n\n::: {.cell-output-display}\n![Altham's Binomial PMFs](Lab10WriteUp_files/figure-pdf/PMFs-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## Part c\nWhat is your best assessment of what $\\theta$ is doing in this setting. Consider when a 6-0 blowout is most likely, and when a 5-6 nail-biter is most likely. Note here we should treat the match as a fixed $n=11$ as we did for $n=3$ in Lab 8.\\\n**Note:** In lab 8, we saw that small $\\theta$ meant wins came in bunches (clumped together), so there were more 2-0 wins in a best of three series.\n\n**Solution**\nA 6-0 blowout is most likely with a small theta, when wins come in clusters(hot hand). We can see on the theta = .5 graph how the extremeties are much more emphasized compared to a higher theta. A higher theta, like 1.5, is a lot more likely to end in a 6-5 score. We can see the 6 wins and 5 wins bars being the most probable on the theta = 1.5 graph because there is less hot hand effect.\n\n# Question 2\n\n## Part a\nAltham's Multiplicative Binomial Distribution does not typically simplify to the clean $E(X)=np$ seen in the Binomial distribution, unless $\\theta = 1$. Write out the expression that would need to be solved to find $E(X^k)$, and then write a function that computes it given the proposed parameter values $p$ (`prob`) and $\\theta$ (`theta`).\n\n**Solution**\n\n$E(X^k) = \\sum_{i=-\\infty}^\\infty {x^k*f_X(x)}$\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nealtbinom = function(k, size, prob,theta){\n  x = 0:size\n  sum(x^k * daltbinom(x, size, prob, theta))\n}\n# check to see if it equals mean of theta .5\nealtbinom(1,11,.5,.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.5\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n\n## Part b\nDescribe how you can use your answer to part a to find Method of Moments estimates for the parameters $p$ and $\\theta$ for Altham's Multiplicative Binomial Distribution based on data.\n\n**Solution**\nBecause we have two unknown parameters, we would need two equations in order to use a system of equations to find their values. We can use the expected value function from part a using k=1 and k=2 to get two equations using two estimators and solve for the values of p and theta that satisfy it.\n\n## Part c\nWrite a function that computes the log-likelihood for Altham's Multiplicative Binomial Distribution, given data (`x`) and proposed parameter values $p$ (`prob`) and $\\theta$ (`theta`).\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nllaltbinom = function(data = x, par, size, mle = F){\n  prob = ifelse(mle, 1 / (1 + exp(-par[1])), par[1])\n  theta = ifelse(mle, exp(par[2]), par[2])\n  \n  ll = sum(log(daltbinom(data,size,prob,theta)))\n\n  ifelse(mle, -ll, ll)\n}\n```\n:::\n\n\n \\normalsize\n\n\n## Part d\nDescribe how you can use your answer to part c to find Maximum Likelihood estimates for the parameters $p$ and $\\theta$ for Altham's Multiplicative Binomial Distribution based on data.\n\n**Solution**\nTo find the mle I would use the optim function setting mle to true. This would contrain the search to 0-1 because of my if else statement and returns the negative log likelihood because optim minimizing by default but the min of the negative function would be the max.\n\n\n# Lab 10\nPeter \"Snakebite\" Wright is a two-time Professional Darts Corporation World Champion (2020, 2022) and a former World No. 1. He is one of the sport's most decorated players, winning nearly 50 PDC titles including the World Matchplay, UK Open, and multiple European Championships. \n\nIn 2024, he made The Premier League -- a league involving the eight best players that runs every Thursday night from February to May. In this season, he won two of eighteen matches, securing only four points. The spread in legs won was -43, meaning he lost 43 more legs than he won. This performance was rather quite bad. He was soundly trounced in almost all his match ups. \n\n\nThe 2024 standings are below:\n\n| Rank | Player             |\n|:-----|:-------------------|\n| 1    |Luke Littler        |\n| 2    |Luke Humphries      |\n| 3    |Michael van Gerwen  |\n| 4    |Michael Smith       |\n| 5    |Nathan Aspinall     |\n| 6    |Rob Cross           |\n| 7    |Gerwyn Price        |\n| 8    |Peter Wright        |\n\n\n## Summarize the 2024 Data\n\nIn `pdc2024.csv`, I have provided the data for the 2024 Premier League season. There are a few data cleaning steps to consider.\n\n  * Remove any matches with no `Score` (e.g., a bye or walkover)\n  * Nights 1 through 16 are best of 11 (first to 6), but the playoffs are extended. For consistency, keep nights 1 through 16 only.\n  * Make two columns `WinnerLegs` and `LoserLegs` that keep track of the number of legs each player has won\n\n  **Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  pdcdata = read.csv(\"pdc2024.csv\")\n  dat.pdc.cleaned = pdcdata |>\n     filter(Night != \"Finals\" & Score != \"w/o\") |>\n     separate(col = \"Score\", into = c(\"WinnerLegs\", \"LoserLegs\"))\n```\n:::\n\n\n \\normalsize\n\nSummarize the data. What do the data tell us about the breakdown of the results?\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.pdc.cleaned |>\n  mutate(\n    WinnerLegs = as.numeric(WinnerLegs),\n    LoserLegs  = as.numeric(LoserLegs)\n  ) |>\n  pivot_longer(\n    cols = c(Winner, Loser),\n    names_to = \"Result\",\n    values_to = \"Player\"\n  ) |>\n  mutate(LegsWon = ifelse(Result == \"Winner\", WinnerLegs, LoserLegs)) |>\n  group_by(Player) |>\n  summarise(TotalLegs = sum(LegsWon)) |>\n  ggplot(aes(x = reorder(Player, TotalLegs), y = TotalLegs)) +\n  geom_col() +\n  coord_flip() +\n  xlab(\"Player\") +\n  ylab(\"Total Legs Won\") +\n  ggtitle(\"Total Legs Won by Player - 2024 PDC Premier League\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Lab10WriteUp_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.pdc.cleaned |>\n  mutate(\n    WinnerLegs = as.numeric(WinnerLegs),\n    LoserLegs  = as.numeric(LoserLegs)\n  ) |>\n  pivot_longer(\n    cols = c(Winner, Loser),\n    names_to = \"Result\",\n    values_to = \"Player\"\n  ) |>\n  mutate(LegsWon = ifelse(Result == \"Winner\", WinnerLegs, LoserLegs)) |>\n  group_by(Player) |>\n  summarise(\n    mean   = mean(LegsWon),\n    sd     = sd(LegsWon),\n    median = median(LegsWon),\n    IQR    = IQR(LegsWon),\n    skew   = e1071::skewness(LegsWon),\n    ekurt  = e1071::kurtosis(LegsWon)\n  ) |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Player             |  mean|    sd| median| IQR|   skew|  ekurt|\n|:------------------|-----:|-----:|------:|---:|------:|------:|\n|Gerwyn Price       | 4.318| 1.585|      5|   3| -0.435| -1.192|\n|Luke Humphries     | 5.281| 1.198|      6|   1| -1.623|  1.466|\n|Luke Littler       | 5.361| 1.073|      6|   1| -1.402|  0.413|\n|Michael Smith      | 4.839| 1.508|      6|   2| -0.921| -0.408|\n|Michael van Gerwen | 4.821| 1.588|      6|   3| -0.788| -1.154|\n|Nathan Aspinall    | 4.931| 1.223|      6|   2| -0.440| -1.544|\n|Peter Wright       | 3.389| 1.614|      4|   2| -0.049| -1.230|\n|Rob Cross          | 4.423| 1.604|      5|   3| -0.509| -1.145|\n\n\n:::\n:::\n\n\n \\normalsize\n\n**Summary**\nOn the graph and the mean of legs won by each player, we can see that the player with the most wins per match is not necessarily the winning player with Michael Smith and Nathan Aspinall winning more games than Michael van Gerwen, and both having a higher mean games won, yet Michael van Gerwen had a higher rank, i.e. he won more matches. \n\n## Altham's Multiplicative Binomial Distribution\nFor each player in the 2024 season, use the number of legs won in each match to compute maximium likelihood estimates for $p$ and $\\theta$. \\\n**Note**: The \"for each\" here can be done more efficiently with a function or a loop!\n\n* Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner's legs and sometimes from the loser's legs.\n* Find the MLE for the player using this data. Ensure to report $p$ and $\\theta$ for each player in a nicely formatted table.\\\n**Note:** In Lecture on Monday, we used transformations to restrict how `optim()` searches the parameter space. For example, here, you might consider\n`p <- 1/(1+exp(-par[1]))` and `theta <- exp(par[2])`.\n* Make comments about the MLEs in the context of the standings.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.legs = dat.pdc.cleaned |>\n  mutate(\n    WinnerLegs = as.numeric(WinnerLegs),\n    LoserLegs  = as.numeric(LoserLegs)\n  ) |>\n  pivot_longer(\n    cols = c(Winner, Loser),\n    names_to = \"Result\",\n    values_to = \"Player\"\n  ) |>\n  mutate(LegsWon = ifelse(Result == \"Winner\", WinnerLegs, LoserLegs))\n\nget.mle = function(player.legs) {\n  fit = optim(\n    par = c(0, 0),\n    fn = function(par) llaltbinom(data = player.legs, par = par, size = 11, mle = TRUE)\n  )\n  list(\n    p     = 1 / (1 + exp(-fit$par[1])),\n    theta = exp(fit$par[2])\n  )\n}\n\nplayers = unique(dat.legs$Player)\n\nmle.results = tibble(\n  Player = players,\n  p      = NA_real_,\n  theta  = NA_real_\n)\n\nfor(i in 1:length(players)){\n  player.legs = dat.legs |>\n    filter(Player == players[i]) |>\n    pull(LegsWon)\n  \n  fit = get.mle(player.legs)\n  mle.results$p[i]     = fit$p\n  mle.results$theta[i] = fit$theta\n}\n\nmle.results |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Player             |     p| theta|\n|:------------------|-----:|-----:|\n|Rob Cross          | 0.395| 1.014|\n|Peter Wright       | 0.317| 0.989|\n|Gerwyn Price       | 0.383| 1.020|\n|Nathan Aspinall    | 0.403| 1.186|\n|Michael Smith      | 0.426| 1.047|\n|Michael van Gerwen | 0.431| 1.023|\n|Luke Littler       | 0.469| 1.316|\n|Luke Humphries     | 0.461| 1.205|\n\n\n:::\n:::\n\n\n \\normalsize\n\n**Comments**\nThe MLE estimates for p align closely with the final standings, higher ranked players tend to have higher estimated leg-winning probabilities, with Littler and Humphries at the top and Wright clearly last. The theta estimates suggest most players exhibit slight clustering (θ > 1), meaning matches tend toward closer scorelines, with Littler and Humphries showing the strongest tendency for closer matches and Peter Wright having the lowest.\n\n\n## Altham's Multiplicative Beta Binomial Distribution\n\nFor each player in the 2024 season, use the number of legs won in each match to compute maxmium likelihood estimates for $p$ and $\\theta$.\\\n**Note**: The \"for each\" here can be done more efficiently with a function or a loop!\n\n* Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner's legs and sometimes from the loser's legs.\n* Find the MLEs for the player using this data. Ensure to report $\\alpha$, $\\beta$, and $\\theta$ for each player in a nicely formatted table.\\\n**Note 1**: Due to the computational complexity of `integrate()`, you should compute the logged probability for `0:6` once and add them according to the data in each player's vector.\n**Note 2**: In Lecture on Monday, we used transformations to restrict how `optim()` searches the parameter space.\n* Plot the underlying Beta($\\alpha$, $\\beta$) distribution for each player. \\\n**Note**: Add the mean and variance of the Beta to the table of MLEs. Recall\n\\begin{align*}\n E(X)   &= \\frac{\\alpha}{\\alpha+\\beta}\\\\\n sd(X) &= \\sqrt{\\frac{\\alpha\\beta}{(\\alpha+\\beta)^2(\\alpha+\\beta+1)}}\n\\end{align*}\n* Make comments about the MLEs in the context of the standings.\\\n**Note**: The players alternate who throws first in a leg has the mathematical \"head start\" to reach a finish before their opponent can take another turn. Players alternate who throws first with each leg.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nllaltbbinom = function(data = x, par, size, mle = F){\n  alpha = ifelse(mle, exp(par[1]), par[1])\n  beta  = ifelse(mle, exp(par[2]), par[2])\n  theta = ifelse(mle, exp(par[3]), par[3])\n\n  log.probs = log(daltbbinom(0:size, size, alpha, beta, theta))\n  \n  ll = sum(log.probs[data + 1])\n  \n  ifelse(mle, -ll, ll)\n}\n\nget.mle.bb = function(player.legs) {\n  fit = optim(\n    par = c(0, 0, 0),\n    fn = function(par) llaltbbinom(data = player.legs, par = par, size = 11, mle = TRUE)\n  )\n  list(\n    alpha = exp(fit$par[1]),\n    beta  = exp(fit$par[2]),\n    theta = exp(fit$par[3])\n  )\n}\n\nmle.results.bb = tibble(\n  Player = players,\n  alpha  = NA_real_,\n  beta   = NA_real_,\n  theta  = NA_real_\n)\n\nfor(i in 1:length(players)){\n  player.legs = dat.legs |>\n    filter(Player == players[i]) |>\n    pull(LegsWon)\n  \n  fit = get.mle.bb(player.legs)\n  mle.results.bb$alpha[i] = fit$alpha\n  mle.results.bb$beta[i]  = fit$beta\n  mle.results.bb$theta[i] = fit$theta\n}\n\nmle.results.bb |>\n  mutate(\n    mean = alpha / (alpha + beta),\n    sd   = sqrt((alpha * beta) / ((alpha + beta)^2 * (alpha + beta + 1)))\n  ) |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Player             | alpha|  beta|  theta|  mean|    sd|\n|:------------------|-----:|-----:|------:|-----:|-----:|\n|Rob Cross          | 0.268| 0.813|  3.202| 0.248| 0.299|\n|Peter Wright       | 1.786| 7.289|  1.214| 0.197| 0.125|\n|Gerwyn Price       | 0.264| 0.917|  3.175| 0.224| 0.282|\n|Nathan Aspinall    | 2.468| 4.338|  1.492| 0.363| 0.172|\n|Michael Smith      | 0.534| 1.068|  2.245| 0.334| 0.292|\n|Michael van Gerwen | 0.219| 0.454|  5.001| 0.325| 0.362|\n|Luke Littler       | 0.283| 0.384| 10.797| 0.425| 0.383|\n|Luke Humphries     | 0.331| 0.490|  6.391| 0.403| 0.363|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\np.seq = seq(0.001, 0.999, length.out = 1000)\n\nggdat.beta = mle.results.bb |>\n  rowwise() |>\n  mutate(density = list(tibble(p = p.seq, \n                               d = dbeta(p.seq, alpha, beta)))) |>\n  unnest(density)\n\nggplot(ggdat.beta, aes(x = p, y = d)) +\n  geom_line() +\n  facet_wrap(~ Player, ncol = 2) +\n  xlab(\"p\") +\n  ylab(\"Density\") +\n  ggtitle(\"Underlying Beta Distribution by Player\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Underlying Beta(alpha, Beta)](Lab10WriteUp_files/figure-pdf/underlying beta-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n**Comments**\nThe mean of the underlying Beta distribution follows the standings closely. Littler with a mean of 0.425 and Humphries with a mean of 0.403 rank the highest, while Wright, whose mean is 0.197, ranks last by a wide margin. The large theta estimates for top players like Littler (θ = 10.797) and Humphries (θ = 6.391) again suggest their matches strongly tend toward close alternating leg patterns. Wright's low Beta distribution (sd = 0.125) suggests his low leg-winning probability was consistent across matches.\n\n## Executive Summary\nSummarize the work you've done here to provide a brief (200-300 word) data-driven summary of the 2024 Premier League season using your work in Lab 10. Your summary should be professional, clear, and all claims should be corroborated with statistical support.\n\n**Summary**\nThe 2024 PDC Premier League season featured eight of the world's best darts players competing across 16 nights of best-of-eleven (first to six legs) matches. Using Altham's Multiplicative Binomial and Altham's Multiplicative Beta Binomial distributions, we estimated each player's leg-winning probability p and clustering parameter theta through the MLE to better understand performance across the season. Looking at the raw data, total legs won by player shows a clear separation between the top and bottom of the standings. Littler and Humphries led in total legs and mean legs won per match(5.36 and 5.28 respectively), while Wright trailed behind by a wide margin. This is consistent with his 2 win finish. Notably, Michael Smith and Nathan Aspinall had higher mean legs won per match(4.84 and 4.931 respectively) than Michael van Gerwen(4.821), despite van Gerwen ranking above both in the end. This suggets he was more efficient at converting close matches into wins, or Nathan Aspinall and Michael Smith had close losses. We can confirm this theory by seeing the theta value for each player being >1 meaning closer matches, except for Peter Wright(.989) who lost many matches by a high differential. The Multiplicative Beta Binomial model adds further nuance by allowing each player's leg-winning probability to vary match-to-match via an underlying Beta distribution. Littler and Humphries had the highest estimated means (0.425 and 0.403 respectively), while Wright's underlying Beta mean near 0.197 with a standard deviation of 0.125, meaning his poor performance was not only low on average but consistently low across all matches. Littler and Humphries also had the largest theta hat estimates (10.797 and 6.391), suggesting their matches were especially prone to tight alternating-leg patterns. ",
    "supporting": [
      "Lab10WriteUp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}