project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  favicon: images/ColgateC.png
  sidebar:
    logo: images/ColgateSeal.png
    style: "docked"
    collapse-level: 1
    search: false
    contents:
    - href: index.qmd
      text: Home
      icon: house
    - href: about.qmd
      text: About
      icon: person
     # MATH 240
    - section: "Computational Statistics"
      contents:
       - text: "Lab 2: Objects in R"
         href: lab2/Lab2WriteUp.qmd
       - text: "Lab 3: Objects in R 2"
         href: lab3/Lab3WriteUp.qmd
       - text: "Lab 4: Programming"
         href: lab4/Lab4WriteUp.qmd
       - text: "Lab 5: Data Wrangling"
         href: lab5/Lab5WriteUp.qmd
       - text: "Lab 8: Probability"
         href: lab8/Lab8WriteUp.qmd
       - text: "Lab 10: Point Estimation"
         href: lab10/Lab10WriteUp.qmd
       - text: "Lab 11: Estimation"
         href: lab11/Lab11WriteUp.qmd
      # MATH 354
    - section: "Data Analysis I"

page-footer:
  left: "© 2026 Colgate University Student Portfolio"
  right: "[GitHub Source](https://github.com/WilliamCipolli)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

