{
  "hash": "9b65d0d9a2566694d7769b0adb66397d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Eleven -- Point Estimation and Resampling # Title of the document\n\n# Bibliography Details\nbibliography: Lab11References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab10WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n\n# Introduction\nWhen performing point estimation, there isn't just one *right* answer. For example, the Method of Moments (MOM) and Maximum Likelihood Estimates (MLEs) aren't always the same.\n\nOne question that comes up, is why we calculate the sample variance as\n$$S_{n-1}^2 = \\frac{1}{n-1} \\sum_{i=1}^n (X_i -\\bar{X})^2,$$\nwhen it is supposed to be the ``average squared distance from the mean, i.e., \n$$S_n^2 = \\frac{1}{n} \\sum_{i=1}^n (X_i -\\bar{X})^2.$$\n\n\n# Comparing Estimators\n\n## Initial Simulation\nIn this lab, we will explore why we use $S_{n-1}^2$ and not $S_n^2$. To do this, we will generate data from four known distributions:\n\n* Poisson$(\\lambda=2)$\n* Binomial$\\left(n=50, p=\\frac{5-\\sqrt{21}}{10}\\right)$\n* Normal$(\\mu=0, \\sigma=\\sqrt{2})$\n* Exponential$\\left(\\lambda = \\frac{1}{\\sqrt{2}}\\right).$\n\n**Remark**: Note that I have selected the parameters so that the true variance for all four models is 2.\n\nFor each distribution, write a loop that completes the following 1000 times. Put `set.seed(7272)` at the top of your code chunk.\n\n* Generate a sample of size $n$ from the distribution.\n* Calculate and save $S_{n-1}^2$ and $S_n^2.$\n\nStart with $n=20$. Is there evidence that $S_{n-1}^2$ is a better estimator than $S_n^2$?\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7272)\nn = 20\n\nSn1pois = numeric(1000)\nSnpois = numeric(1000)\nSn1binom = numeric(1000)\nSnbinom = numeric(1000)\nSn1norm = numeric(1000)\nSnnorm = numeric(1000)\nSn1exp = numeric(1000)\nSnexp = numeric(1000)\n\n\nfor(i in 1:1000){\npois = rpois(n,2)\nbinom = rbinom(n,50,(5-sqrt(21))/10)\nnorm = rnorm(n,0,sqrt(2))\nexp = rexp(n,1/(sqrt(2)))\n\n          Sn1pois[i] = var(pois)\n          Snpois[i] = (n-1)/n * var(pois)\n          Sn1binom[i] = var(binom)\n          Snbinom[i] = (n-1)/n * var(binom)\n          Sn1norm[i] = var(norm)\n          Snnorm[i] = (n-1)/n * var(norm)\n          Sn1exp[i] = var(exp)\n          Snexp[i] = (n-1)/n * var(exp)\n\n}\nresults = tibble(Sn1pois,\n                 Snpois,\n                 Sn1binom,\n                 Snbinom,\n                 Sn1norm,\n                 Snnorm,\n                 Sn1exp,\n                 Snexp)\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 8\n   Sn1pois Snpois Sn1binom Snbinom Sn1norm Snnorm Sn1exp Snexp\n     <dbl>  <dbl>    <dbl>   <dbl>   <dbl>  <dbl>  <dbl> <dbl>\n 1    1.40   1.33    2.66    2.53     2.80   2.66  2.18  2.07 \n 2    3.46   3.29    1.52    1.44     2.14   2.03  2.95  2.81 \n 3    1.37   1.3     1.82    1.73     1.65   1.57  3.95  3.75 \n 4    1.82   1.73    1.04    0.987    1.87   1.77  2.68  2.55 \n 5    2.24   2.13    0.787   0.748    1.44   1.37  0.427 0.406\n 6    2.05   1.95    2.37    2.25     2.13   2.02  1.09  1.03 \n 7    1.46   1.39    1.08    1.03     1.13   1.08  2.89  2.74 \n 8    3.06   2.91    1.41    1.34     2.34   2.22  1.43  1.36 \n 9    1.71   1.63    1.33    1.26     1.83   1.73  2.01  1.91 \n10    1.08   1.03    1.01    0.96     1.33   1.26  1.25  1.19 \n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary = tibble(\n  Distribution = c(\"Poisson\", \"Binomial\", \"Normal\", \"Exponential\"),\n  \n  BiasSn1 = c(mean(Sn1pois)  - 2,\n               mean(Sn1binom) - 2,\n               mean(Sn1norm)  - 2,\n               mean(Sn1exp)   - 2),\n  \n  BiasSn = c(mean(Snpois)  - 2,\n              mean(Snbinom) - 2,\n              mean(Snnorm)  - 2,\n              mean(Snexp)   - 2),\n  \n  PrecisionSn1 = c(1/var(Sn1pois),\n                    1/var(Sn1binom),\n                    1/var(Sn1norm),\n                    1/var(Sn1exp)),\n  \n  PrecisionSn = c(1/var(Snpois),\n                   1/var(Snbinom),\n                   1/var(Snnorm),\n                   1/var(Snexp)),\n  \n  MSESn1 = c(BiasSn1[1]^2 + var(Sn1pois),\n              BiasSn1[2]^2 + var(Sn1binom),\n              BiasSn1[3]^2 + var(Sn1norm),\n              BiasSn1[4]^2 + var(Sn1exp)),\n  \n  MSESn = c(BiasSn[1]^2 + var(Snpois),\n             BiasSn[2]^2 + var(Snbinom),\n             BiasSn[3]^2 + var(Snnorm),\n             BiasSn[4]^2 + var(Snexp))\n)\nsummary |>\n  knitr::kable(\n    col.names = c(\"Distribution\", \n                  \"Bias (Sn1)\", \"Bias (Sn)\", \n                  \"Precision (Sn1)\", \"Precision (Sn)\",\n                  \"MSE (Sn1)\", \"MSE (Sn)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Distribution | Bias (Sn1)|  Bias (Sn)| Precision (Sn1)| Precision (Sn)| MSE (Sn1)|  MSE (Sn)|\n|:------------|----------:|----------:|---------------:|--------------:|---------:|---------:|\n|Poisson      | -0.0767447| -0.1729075|       2.0849339|      2.3101761| 0.4855213| 0.4627644|\n|Binomial     |  0.0043132| -0.0959025|       1.8697049|      2.0716952| 0.5348624| 0.4918938|\n|Normal       |  0.0008472| -0.0991952|       2.5487945|      2.8241490| 0.3923431| 0.3639287|\n|Exponential  |  0.0185396| -0.0823874|       0.6448663|      0.7145333| 1.5510527| 1.4063026|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n\nCreate a plot or combination of plots (using patchwork) to show the results across all four distributions. Make sure to create a corresponding table that numerically summarizes the results of the simulation. You should include\n\\begin{align*}\n\\textrm{Bias} &= \\textrm{Average of Estimates} - \\textrm{True Value}\\\\\n\\textrm{Precision} &= \\frac{1}{\\textrm{Variance of Estimates}}\\\\\n\\textrm{Mean Square Error} &= \\textrm{Bias}^2 + \\textrm{Variance of Estimates}.\n\\end{align*}\n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='110%'}\n\n```{.r .cell-code}\np1 = ggplot(results) +\n  geom_density(aes(x = Sn1pois, color = \"Sn1\")) +\n  geom_density(aes(x = Snpois, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Poisson\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np2 = ggplot(results) +\n  geom_density(aes(x = Sn1binom, color = \"Sn1\")) +\n  geom_density(aes(x = Snbinom, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Binomial\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np3 = ggplot(results) +\n  geom_density(aes(x = Sn1norm, color = \"Sn1\")) +\n  geom_density(aes(x = Snnorm, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Normal\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np4 = ggplot(results) +\n  geom_density(aes(x = Sn1exp, color = \"Sn1\")) +\n  geom_density(aes(x = Snexp, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Exponential\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\n(p1 + p2) / (p3 + p4)\n```\n\n::: {.cell-output-display}\n![Comparison](Lab11WriteUp_files/figure-html/plots-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n \\normalsize\n\n## Simulation over various sample sizes\nConsider the effect of the sample size have on these results. Provide a graphical and numerical summary of what happens as $n$ increases -- say $n=20$, $n=50$, $n=100$, and $n=500$. Does the result in your initial simulation hold across samples? Or, do things change as the sample size changes? Ensure to set your randomization seed.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 20\nset.seed(7272)\nn = 20\n\nSn1pois = numeric(1000)\nSnpois = numeric(1000)\nSn1binom = numeric(1000)\nSnbinom = numeric(1000)\nSn1norm = numeric(1000)\nSnnorm = numeric(1000)\nSn1exp = numeric(1000)\nSnexp = numeric(1000)\n\n\nfor(i in 1:1000){\npois = rpois(n,2)\nbinom = rbinom(n,50,(5-sqrt(21))/10)\nnorm = rnorm(n,0,sqrt(2))\nexp = rexp(n,1/(sqrt(2)))\n\n          Sn1pois[i] = var(pois)\n          Snpois[i] = (n-1)/n * var(pois)\n          Sn1binom[i] = var(binom)\n          Snbinom[i] = (n-1)/n * var(binom)\n          Sn1norm[i] = var(norm)\n          Snnorm[i] = (n-1)/n * var(norm)\n          Sn1exp[i] = var(exp)\n          Snexp[i] = (n-1)/n * var(exp)\n\n}\nresults = tibble(Sn1pois,\n                 Snpois,\n                 Sn1binom,\n                 Snbinom,\n                 Sn1norm,\n                 Snnorm,\n                 Sn1exp,\n                 Snexp)\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 8\n   Sn1pois Snpois Sn1binom Snbinom Sn1norm Snnorm Sn1exp Snexp\n     <dbl>  <dbl>    <dbl>   <dbl>   <dbl>  <dbl>  <dbl> <dbl>\n 1    1.40   1.33    2.66    2.53     2.80   2.66  2.18  2.07 \n 2    3.46   3.29    1.52    1.44     2.14   2.03  2.95  2.81 \n 3    1.37   1.3     1.82    1.73     1.65   1.57  3.95  3.75 \n 4    1.82   1.73    1.04    0.987    1.87   1.77  2.68  2.55 \n 5    2.24   2.13    0.787   0.748    1.44   1.37  0.427 0.406\n 6    2.05   1.95    2.37    2.25     2.13   2.02  1.09  1.03 \n 7    1.46   1.39    1.08    1.03     1.13   1.08  2.89  2.74 \n 8    3.06   2.91    1.41    1.34     2.34   2.22  1.43  1.36 \n 9    1.71   1.63    1.33    1.26     1.83   1.73  2.01  1.91 \n10    1.08   1.03    1.01    0.96     1.33   1.26  1.25  1.19 \n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary1 = tibble(\n  Distribution = c(\"Poisson\", \"Binomial\", \"Normal\", \"Exponential\"),\n  \n  BiasSn1 = c(mean(Sn1pois)  - 2,\n               mean(Sn1binom) - 2,\n               mean(Sn1norm)  - 2,\n               mean(Sn1exp)   - 2),\n  \n  BiasSn = c(mean(Snpois)  - 2,\n              mean(Snbinom) - 2,\n              mean(Snnorm)  - 2,\n              mean(Snexp)   - 2),\n  \n  PrecisionSn1 = c(1/var(Sn1pois),\n                    1/var(Sn1binom),\n                    1/var(Sn1norm),\n                    1/var(Sn1exp)),\n  \n  PrecisionSn = c(1/var(Snpois),\n                   1/var(Snbinom),\n                   1/var(Snnorm),\n                   1/var(Snexp)),\n  \n  MSESn1 = c(BiasSn1[1]^2 + var(Sn1pois),\n              BiasSn1[2]^2 + var(Sn1binom),\n              BiasSn1[3]^2 + var(Sn1norm),\n              BiasSn1[4]^2 + var(Sn1exp)),\n  \n  MSESn = c(BiasSn[1]^2 + var(Snpois),\n             BiasSn[2]^2 + var(Snbinom),\n             BiasSn[3]^2 + var(Snnorm),\n             BiasSn[4]^2 + var(Snexp))\n)\nsummary1 |>\n  knitr::kable(\n    col.names = c(\"Distribution\", \n                  \"Bias (Sn1)\", \"Bias (Sn)\", \n                  \"Precision (Sn1)\", \"Precision (Sn)\",\n                  \"MSE (Sn1)\", \"MSE (Sn)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Distribution | Bias (Sn1)|  Bias (Sn)| Precision (Sn1)| Precision (Sn)| MSE (Sn1)|  MSE (Sn)|\n|:------------|----------:|----------:|---------------:|--------------:|---------:|---------:|\n|Poisson      | -0.0767447| -0.1729075|       2.0849339|      2.3101761| 0.4855213| 0.4627644|\n|Binomial     |  0.0043132| -0.0959025|       1.8697049|      2.0716952| 0.5348624| 0.4918938|\n|Normal       |  0.0008472| -0.0991952|       2.5487945|      2.8241490| 0.3923431| 0.3639287|\n|Exponential  |  0.0185396| -0.0823874|       0.6448663|      0.7145333| 1.5510527| 1.4063026|\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='110%'}\n\n```{.r .cell-code}\np1 = ggplot(results) +\n  geom_density(aes(x = Sn1pois, color = \"Sn1\")) +\n  geom_density(aes(x = Snpois, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Poisson\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np2 = ggplot(results) +\n  geom_density(aes(x = Sn1binom, color = \"Sn1\")) +\n  geom_density(aes(x = Snbinom, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Binomial\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np3 = ggplot(results) +\n  geom_density(aes(x = Sn1norm, color = \"Sn1\")) +\n  geom_density(aes(x = Snnorm, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Normal\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np4 = ggplot(results) +\n  geom_density(aes(x = Sn1exp, color = \"Sn1\")) +\n  geom_density(aes(x = Snexp, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Exponential\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\n(p1 + p2) / (p3 + p4)\n```\n\n::: {.cell-output-display}\n![n = 20 graphs](Lab11WriteUp_files/figure-html/n20-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n \\normalsize\n\n\n\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 50\nset.seed(7272)\nn = 50\n\nSn1pois = numeric(1000)\nSnpois = numeric(1000)\nSn1binom = numeric(1000)\nSnbinom = numeric(1000)\nSn1norm = numeric(1000)\nSnnorm = numeric(1000)\nSn1exp = numeric(1000)\nSnexp = numeric(1000)\n\n\nfor(i in 1:1000){\npois = rpois(n,2)\nbinom = rbinom(n,50,(5-sqrt(21))/10)\nnorm = rnorm(n,0,sqrt(2))\nexp = rexp(n,1/(sqrt(2)))\n\n          Sn1pois[i] = var(pois)\n          Snpois[i] = (n-1)/n * var(pois)\n          Sn1binom[i] = var(binom)\n          Snbinom[i] = (n-1)/n * var(binom)\n          Sn1norm[i] = var(norm)\n          Snnorm[i] = (n-1)/n * var(norm)\n          Sn1exp[i] = var(exp)\n          Snexp[i] = (n-1)/n * var(exp)\n\n}\nresults = tibble(Sn1pois,\n                 Snpois,\n                 Sn1binom,\n                 Snbinom,\n                 Sn1norm,\n                 Snnorm,\n                 Sn1exp,\n                 Snexp)\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 8\n   Sn1pois Snpois Sn1binom Snbinom Sn1norm Snnorm Sn1exp Snexp\n     <dbl>  <dbl>    <dbl>   <dbl>   <dbl>  <dbl>  <dbl> <dbl>\n 1    2.38   2.33     2.27    2.23    1.97   1.93  1.57  1.53 \n 2    2.31   2.27     2.14    2.10    1.67   1.63  2.82  2.76 \n 3    2.21   2.17     2.13    2.09    1.53   1.50  1.93  1.89 \n 4    2.12   2.08     1.46    1.43    2.22   2.18  1.14  1.11 \n 5    1.56   1.53     1.55    1.52    1.54   1.51  1.23  1.21 \n 6    2.25   2.20     2.16    2.12    2.42   2.37  2.71  2.65 \n 7    1.99   1.95     1.40    1.37    2.38   2.33  1.93  1.89 \n 8    1.43   1.40     1.87    1.83    2.60   2.55  0.716 0.702\n 9    2.64   2.59     1.97    1.93    1.50   1.47  3.82  3.75 \n10    1.88   1.84     1.59    1.56    2.74   2.68  1.52  1.49 \n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary2 = tibble(\n  Distribution = c(\"Poisson\", \"Binomial\", \"Normal\", \"Exponential\"),\n  \n  BiasSn1 = c(mean(Sn1pois)  - 2,\n               mean(Sn1binom) - 2,\n               mean(Sn1norm)  - 2,\n               mean(Sn1exp)   - 2),\n  \n  BiasSn = c(mean(Snpois)  - 2,\n              mean(Snbinom) - 2,\n              mean(Snnorm)  - 2,\n              mean(Snexp)   - 2),\n  \n  PrecisionSn1 = c(1/var(Sn1pois),\n                    1/var(Sn1binom),\n                    1/var(Sn1norm),\n                    1/var(Sn1exp)),\n  \n  PrecisionSn = c(1/var(Snpois),\n                   1/var(Snbinom),\n                   1/var(Snnorm),\n                   1/var(Snexp)),\n  \n  MSESn1 = c(BiasSn1[1]^2 + var(Sn1pois),\n              BiasSn1[2]^2 + var(Sn1binom),\n              BiasSn1[3]^2 + var(Sn1norm),\n              BiasSn1[4]^2 + var(Sn1exp)),\n  \n  MSESn = c(BiasSn[1]^2 + var(Snpois),\n             BiasSn[2]^2 + var(Snbinom),\n             BiasSn[3]^2 + var(Snnorm),\n             BiasSn[4]^2 + var(Snexp))\n)\nsummary2 |>\n  knitr::kable(\n    col.names = c(\"Distribution\", \n                  \"Bias (Sn1)\", \"Bias (Sn)\", \n                  \"Precision (Sn1)\", \"Precision (Sn)\",\n                  \"MSE (Sn1)\", \"MSE (Sn)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Distribution | Bias (Sn1)|  Bias (Sn)| Precision (Sn1)| Precision (Sn)| MSE (Sn1)|  MSE (Sn)|\n|:------------|----------:|----------:|---------------:|--------------:|---------:|---------:|\n|Poisson      | -0.0100984| -0.0498964|        5.017008|       5.223873| 0.1994240| 0.1939185|\n|Binomial     | -0.0074641| -0.0473148|        5.304907|       5.523643| 0.1885604| 0.1832786|\n|Normal       | -0.0302580| -0.0696528|        6.321937|       6.582608| 0.1590949| 0.1567670|\n|Exponential  | -0.0066077| -0.0464755|        1.528231|       1.591245| 0.6543948| 0.6305988|\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='110%'}\n\n```{.r .cell-code}\np1 = ggplot(results) +\n  geom_density(aes(x = Sn1pois, color = \"Sn1\")) +\n  geom_density(aes(x = Snpois, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Poisson\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np2 = ggplot(results) +\n  geom_density(aes(x = Sn1binom, color = \"Sn1\")) +\n  geom_density(aes(x = Snbinom, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Binomial\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np3 = ggplot(results) +\n  geom_density(aes(x = Sn1norm, color = \"Sn1\")) +\n  geom_density(aes(x = Snnorm, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Normal\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np4 = ggplot(results) +\n  geom_density(aes(x = Sn1exp, color = \"Sn1\")) +\n  geom_density(aes(x = Snexp, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Exponential\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\n(p1 + p2) / (p3 + p4)\n```\n\n::: {.cell-output-display}\n![n = 50 graphs](Lab11WriteUp_files/figure-html/n50-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n \\normalsize\n\n\n\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 100\nset.seed(7272)\nn = 100\n\nSn1pois = numeric(1000)\nSnpois = numeric(1000)\nSn1binom = numeric(1000)\nSnbinom = numeric(1000)\nSn1norm = numeric(1000)\nSnnorm = numeric(1000)\nSn1exp = numeric(1000)\nSnexp = numeric(1000)\n\n\nfor(i in 1:1000){\npois = rpois(n,2)\nbinom = rbinom(n,50,(5-sqrt(21))/10)\nnorm = rnorm(n,0,sqrt(2))\nexp = rexp(n,1/(sqrt(2)))\n\n          Sn1pois[i] = var(pois)\n          Snpois[i] = (n-1)/n * var(pois)\n          Sn1binom[i] = var(binom)\n          Snbinom[i] = (n-1)/n * var(binom)\n          Sn1norm[i] = var(norm)\n          Snnorm[i] = (n-1)/n * var(norm)\n          Sn1exp[i] = var(exp)\n          Snexp[i] = (n-1)/n * var(exp)\n\n}\nresults = tibble(Sn1pois,\n                 Snpois,\n                 Sn1binom,\n                 Snbinom,\n                 Sn1norm,\n                 Snnorm,\n                 Sn1exp,\n                 Snexp)\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 8\n   Sn1pois Snpois Sn1binom Snbinom Sn1norm Snnorm Sn1exp Snexp\n     <dbl>  <dbl>    <dbl>   <dbl>   <dbl>  <dbl>  <dbl> <dbl>\n 1    2.32   2.30     2.31    2.29    2.14   2.12   2.49  2.46\n 2    2.10   2.08     1.29    1.28    1.77   1.75   1.30  1.28\n 3    1.60   1.58     2.43    2.40    2.10   2.08   2.57  2.55\n 4    2.04   2.02     1.78    1.76    1.75   1.73   1.10  1.09\n 5    1.89   1.87     1.67    1.65    2.12   2.10   1.48  1.47\n 6    2.07   2.05     2.01    1.99    1.36   1.35   1.49  1.48\n 7    2.12   2.10     2.42    2.39    2.51   2.48   1.33  1.32\n 8    1.69   1.68     1.55    1.53    2.14   2.12   1.46  1.44\n 9    2.08   2.06     1.82    1.80    1.95   1.93   1.95  1.93\n10    2.61   2.58     2.40    2.37    1.62   1.61   2.56  2.54\n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary3 = tibble(\n  Distribution = c(\"Poisson\", \"Binomial\", \"Normal\", \"Exponential\"),\n  \n  BiasSn1 = c(mean(Sn1pois)  - 2,\n               mean(Sn1binom) - 2,\n               mean(Sn1norm)  - 2,\n               mean(Sn1exp)   - 2),\n  \n  BiasSn = c(mean(Snpois)  - 2,\n              mean(Snbinom) - 2,\n              mean(Snnorm)  - 2,\n              mean(Snexp)   - 2),\n  \n  PrecisionSn1 = c(1/var(Sn1pois),\n                    1/var(Sn1binom),\n                    1/var(Sn1norm),\n                    1/var(Sn1exp)),\n  \n  PrecisionSn = c(1/var(Snpois),\n                   1/var(Snbinom),\n                   1/var(Snnorm),\n                   1/var(Snexp)),\n  \n  MSESn1 = c(BiasSn1[1]^2 + var(Sn1pois),\n              BiasSn1[2]^2 + var(Sn1binom),\n              BiasSn1[3]^2 + var(Sn1norm),\n              BiasSn1[4]^2 + var(Sn1exp)),\n  \n  MSESn = c(BiasSn[1]^2 + var(Snpois),\n             BiasSn[2]^2 + var(Snbinom),\n             BiasSn[3]^2 + var(Snnorm),\n             BiasSn[4]^2 + var(Snexp))\n)\nsummary3 |>\n  knitr::kable(\n    col.names = c(\"Distribution\", \n                  \"Bias (Sn1)\", \"Bias (Sn)\", \n                  \"Precision (Sn1)\", \"Precision (Sn)\",\n                  \"MSE (Sn1)\", \"MSE (Sn)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Distribution | Bias (Sn1)|  Bias (Sn)| Precision (Sn1)| Precision (Sn)| MSE (Sn1)|  MSE (Sn)|\n|:------------|----------:|----------:|---------------:|--------------:|---------:|---------:|\n|Poisson      | -0.0117445| -0.0316271|        9.644444|       9.840266| 0.1038246| 0.1026235|\n|Binomial     | -0.0107295| -0.0306222|        9.688138|       9.884846| 0.1033341| 0.1021027|\n|Normal       | -0.0087292| -0.0286419|       12.345795|      12.596465| 0.0810754| 0.0802077|\n|Exponential  | -0.0060288| -0.0259685|        2.950487|       3.010394| 0.3389635| 0.3328568|\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='110%'}\n\n```{.r .cell-code}\np1 = ggplot(results) +\n  geom_density(aes(x = Sn1pois, color = \"Sn1\")) +\n  geom_density(aes(x = Snpois, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Poisson\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np2 = ggplot(results) +\n  geom_density(aes(x = Sn1binom, color = \"Sn1\")) +\n  geom_density(aes(x = Snbinom, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Binomial\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np3 = ggplot(results) +\n  geom_density(aes(x = Sn1norm, color = \"Sn1\")) +\n  geom_density(aes(x = Snnorm, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Normal\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np4 = ggplot(results) +\n  geom_density(aes(x = Sn1exp, color = \"Sn1\")) +\n  geom_density(aes(x = Snexp, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Exponential\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\n(p1 + p2) / (p3 + p4)\n```\n\n::: {.cell-output-display}\n![n = 100 graphs](Lab11WriteUp_files/figure-html/n100-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n \\normalsize\n\n\n\n\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 500\nset.seed(7272)\nn = 500\n\nSn1pois = numeric(1000)\nSnpois = numeric(1000)\nSn1binom = numeric(1000)\nSnbinom = numeric(1000)\nSn1norm = numeric(1000)\nSnnorm = numeric(1000)\nSn1exp = numeric(1000)\nSnexp = numeric(1000)\n\n\nfor(i in 1:1000){\npois = rpois(n,2)\nbinom = rbinom(n,50,(5-sqrt(21))/10)\nnorm = rnorm(n,0,sqrt(2))\nexp = rexp(n,1/(sqrt(2)))\n\n          Sn1pois[i] = var(pois)\n          Snpois[i] = (n-1)/n * var(pois)\n          Sn1binom[i] = var(binom)\n          Snbinom[i] = (n-1)/n * var(binom)\n          Sn1norm[i] = var(norm)\n          Snnorm[i] = (n-1)/n * var(norm)\n          Sn1exp[i] = var(exp)\n          Snexp[i] = (n-1)/n * var(exp)\n\n}\nresults = tibble(Sn1pois,\n                 Snpois,\n                 Sn1binom,\n                 Snbinom,\n                 Sn1norm,\n                 Snnorm,\n                 Sn1exp,\n                 Snexp)\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 8\n   Sn1pois Snpois Sn1binom Snbinom Sn1norm Snnorm Sn1exp Snexp\n     <dbl>  <dbl>    <dbl>   <dbl>   <dbl>  <dbl>  <dbl> <dbl>\n 1    1.95   1.95     1.77    1.77    1.98   1.97   1.75  1.75\n 2    1.99   1.99     2.12    2.12    1.87   1.87   2.21  2.21\n 3    2.15   2.15     1.99    1.99    2.06   2.06   1.98  1.97\n 4    1.88   1.88     2.08    2.08    2.08   2.08   1.75  1.74\n 5    1.94   1.93     2.09    2.09    1.77   1.77   1.69  1.69\n 6    2.03   2.03     2.12    2.12    2.03   2.03   2.12  2.12\n 7    2.08   2.07     1.99    1.98    1.96   1.95   2.18  2.17\n 8    1.93   1.93     2.07    2.07    1.92   1.92   1.71  1.71\n 9    2.21   2.20     1.91    1.90    1.99   1.99   2.28  2.28\n10    1.83   1.83     2.08    2.07    1.67   1.67   2.00  1.99\n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary4 = tibble(\n  Distribution = c(\"Poisson\", \"Binomial\", \"Normal\", \"Exponential\"),\n  \n  BiasSn1 = c(mean(Sn1pois)  - 2,\n               mean(Sn1binom) - 2,\n               mean(Sn1norm)  - 2,\n               mean(Sn1exp)   - 2),\n  \n  BiasSn = c(mean(Snpois)  - 2,\n              mean(Snbinom) - 2,\n              mean(Snnorm)  - 2,\n              mean(Snexp)   - 2),\n  \n  PrecisionSn1 = c(1/var(Sn1pois),\n                    1/var(Sn1binom),\n                    1/var(Sn1norm),\n                    1/var(Sn1exp)),\n  \n  PrecisionSn = c(1/var(Snpois),\n                   1/var(Snbinom),\n                   1/var(Snnorm),\n                   1/var(Snexp)),\n  \n  MSESn1 = c(BiasSn1[1]^2 + var(Sn1pois),\n              BiasSn1[2]^2 + var(Sn1binom),\n              BiasSn1[3]^2 + var(Sn1norm),\n              BiasSn1[4]^2 + var(Sn1exp)),\n  \n  MSESn = c(BiasSn[1]^2 + var(Snpois),\n             BiasSn[2]^2 + var(Snbinom),\n             BiasSn[3]^2 + var(Snnorm),\n             BiasSn[4]^2 + var(Snexp))\n)\nsummary4 |>\n  knitr::kable(\n    col.names = c(\"Distribution\", \n                  \"Bias (Sn1)\", \"Bias (Sn)\", \n                  \"Precision (Sn1)\", \"Precision (Sn)\",\n                  \"MSE (Sn1)\", \"MSE (Sn)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Distribution | Bias (Sn1)|  Bias (Sn)| Precision (Sn1)| Precision (Sn)| MSE (Sn1)|  MSE (Sn)|\n|:------------|----------:|----------:|---------------:|--------------:|---------:|---------:|\n|Poisson      |  0.0050139|  0.0010039|        50.55808|       50.76092| 0.0198044| 0.0197012|\n|Binomial     |  0.0025404| -0.0014647|        53.19768|       53.41111| 0.0188043| 0.0187248|\n|Normal       |  0.0050610|  0.0010509|        62.32607|       62.57612| 0.0160703| 0.0159816|\n|Exponential  |  0.0022320| -0.0017725|        15.59342|       15.65598| 0.0641346| 0.0638765|\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='110%'}\n\n```{.r .cell-code}\np1 = ggplot(results) +\n  geom_density(aes(x = Sn1pois, color = \"Sn1\")) +\n  geom_density(aes(x = Snpois, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Poisson\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np2 = ggplot(results) +\n  geom_density(aes(x = Sn1binom, color = \"Sn1\")) +\n  geom_density(aes(x = Snbinom, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Binomial\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np3 = ggplot(results) +\n  geom_density(aes(x = Sn1norm, color = \"Sn1\")) +\n  geom_density(aes(x = Snnorm, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Normal\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\np4 = ggplot(results) +\n  geom_density(aes(x = Sn1exp, color = \"Sn1\")) +\n  geom_density(aes(x = Snexp, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Exponential\", x = \"Estimate\", y = \"Density\", fill = \"Estimator\")\n\n(p1 + p2) / (p3 + p4)\n```\n\n::: {.cell-output-display}\n![n = 500 graphs](Lab11WriteUp_files/figure-html/n500-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n \\normalsize\nAs n increases from 20 to 500, the bias of Sn-1​ stays close to 0 across all four distributions, while the bias of Sn​ is consistently negative but larger than Sn-1(except at n=500). For example, in the Poisson case the bias of Sn​ goes from -0.1729 at n=20 down to 0.0010 at n=500. Both estimators become more precise and have lower MSE as n increases. Both are nearly identical across all four distributions, since n-1/n = 499/500 which is approximately 1. So yes, the result from the initial simulation holds that Sn-1 is better than Sn.\n\n \n## Simulation\nYou have written code to draw a random sample of various sizes from each distribution, and to calculate and store the calculated estimates. Rework your code to produce a density plot of the $s_{n-1}^2$ and $s_{n}^2$. Do you have a guess about their distribution? Ensure to set your randomization seed. \n\n**Solution**\nI had done density plots thoughout, here is the comments on those plots. The distributions are right-skewed at small n, but become more symmetric and bell-shaped as n increases. The graphs begin looking approximately normal for large degrees of freedom. This is similar to a chi-squared distribution.\n\n## Bootstrap\nNow, take *one* sample from each distribution. Instead of drawing a random sample at each iteration, sample *with replacement* from the one sample. Produce a density plot of the $s_{n-1}^2$ and $s_{n}^2$. Do we get roughly the same information as we do in the full simulation? Try this over several seeds -- what do you notice? Ensure to set your randomization seed.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7272)\nn = 20\n\npois_samp = rpois(n,2)\nbinom_samp = rbinom(n,50,(5-sqrt(21))/10)\nnorm_samp = rnorm(n,0,sqrt(2))\nexp_samp = rexp(n,1/(sqrt(2)))\n\nSn1pois = numeric(1000)\nSnpois = numeric(1000)\nSn1binom = numeric(1000)\nSnbinom = numeric(1000)\nSn1norm = numeric(1000)\nSnnorm = numeric(1000)\nSn1exp = numeric(1000)\nSnexp = numeric(1000)\n\nfor(i in 1:1000){\n  pois = sample(pois_samp, n, replace = TRUE)\n  binom = sample(binom_samp, n, replace = TRUE)\n  norm = sample(norm_samp, n, replace = TRUE)\n  exp = sample(exp_samp, n, replace = TRUE)\n\n  Sn1pois[i] = var(pois)\n  Snpois[i] = (n-1)/n * var(pois)\n  Sn1binom[i] = var(binom)\n  Snbinom[i] = (n-1)/n * var(binom)\n  Sn1norm[i] = var(norm)\n  Snnorm[i] = (n-1)/n * var(norm)\n  Sn1exp[i] = var(exp)\n  Snexp[i] = (n-1)/n * var(exp)\n}\n\nboot_results = tibble(Sn1pois,\n                      Snpois,\n                      Sn1binom,\n                      Snbinom,\n                      Sn1norm,\n                      Snnorm,\n                      Sn1exp,\n                      Snexp)\n```\n:::\n\n\n \\normalsize\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='110%'}\n\n```{.r .cell-code}\np1 = ggplot(boot_results) +\n  geom_density(aes(x = Sn1pois, color = \"Sn1\")) +\n  geom_density(aes(x = Snpois, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Poisson\", x = \"Estimate\", y = \"Density\", color = \"Estimator\")\n\np2 = ggplot(boot_results) +\n  geom_density(aes(x = Sn1binom, color = \"Sn1\")) +\n  geom_density(aes(x = Snbinom, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Binomial\", x = \"Estimate\", y = \"Density\", color = \"Estimator\")\n\np3 = ggplot(boot_results) +\n  geom_density(aes(x = Sn1norm, color = \"Sn1\")) +\n  geom_density(aes(x = Snnorm, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Normal\", x = \"Estimate\", y = \"Density\", color = \"Estimator\")\n\np4 = ggplot(boot_results) +\n  geom_density(aes(x = Sn1exp, color = \"Sn1\")) +\n  geom_density(aes(x = Snexp, color = \"Sn\")) +\n  geom_vline(xintercept = 2, linetype = \"dashed\") +\n  labs(title = \"Exponential\", x = \"Estimate\", y = \"Density\", color = \"Estimator\")\n\n(p1 + p2) / (p3 + p4)\n```\n\n::: {.cell-output-display}\n![Bootstrapping graphs](Lab11WriteUp_files/figure-html/Bootstrapping-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n \\normalsize\nTrying this over several seeds, I notice that the bootstrap distributions are always centered around the sample variance of the original sample rather than the true variance of 2. When the original sample happens to have a variance close to 2, the bootstrap looks very similar to the full simulation. When the original sample has a variance far from 2, the bootstrap center shifts noticeably away from 2. \n\n\n# Executive Summary\nSummarize the work you've done here to provide a brief (200-300 word) summary of the simulation and the results using your work in Lab 11. Your summary should be professional, clear, and all claims should be corroborated with statistical support.\n\n**Solution**\nThis simulation study compared two estimators of population variance, Sn-1\nSn​, across four distributions — Poisson(λ=2), Binomial(n=50, p=5−root21 / 10​​), Normal(μ=0, σ=2), and Exponential(λ=1/root2​), all with a true variance of 2. At n=20 Sn−1 was approximately unbiased across all four distributions, while Sn was consistently negatively biased. For example, in the Poisson graphs the bias of Sn​ was -0.1729 compared to -0.0767 for Sn−1​. As n increased to 50, 100, and 500, both estimators converged toward the true variance of 2 and became nearly indistinguishable, since 499/500 is basically 1. The density plots suggest both estimators follow a chi-squared distribution: right-skewed at small n but becoming approximately normal as n grows. Finally, the bootstrap analysis showed that resampling with replacement from a single sample captures a similar shape to the full simulation, but the center of the bootstrap distribution depends on the original sample drawn rather than the true variance of 2, shifting noticeably across different seeds.",
    "supporting": [
      "Lab11WriteUp_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}