{
  "hash": "fcf76a97ac2d78dd4511f8333720cdd5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Thirteen -- Statistical Inference # Title of the document\n\n# Bibliography Details\nbibliography: Lab13References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab10WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n# Remaining Portfolio Work!\n\n**By 5p 4/27** Email me a link to your GitHub page with all polished labs rendered, and your review material (at least one unit). In the email, you should include a reflection about the processes involved in creating this portfolio and what you learned as a result. If you're having trouble reflecting, consider Fink's Taxonomy of Significant Learning (Google Fink taxonomy aligned self-reflection questions). In the email, let me know whether you would be comfortable sharing your page -- I'm hoping that together we can get a good study guide for the final.\n\n# Statistical Inference\n\n@Kasdin25 show that dopamine in the brains of young zebra finches acts as \na learning signal, increasing when they sing closer to their adult song and \ndecreasing when they sing further away, effectively guiding their vocal \ndevelopment through trial-and-error. This suggests that complex natural \nbehaviors, like learning to sing, are shaped by dopamine-driven reinforcement \nlearning, similar to how artificial intelligence learns. You can find the \npaper at this link: [https://www.nature.com/articles/s41586-025-08729-1](https://www.nature.com/articles/s41586-025-08729-1).\n\nNote that the measurement is rather complicated. First, the measurements are taken on syllables of a bird song. When discussing bird songs, the term syllable refers to a single, distinct, uninterrupted sound that is part of a\npossibly complex bird song.\n\nThey initially describe their measurement as follows. They compare the sound of the developing zebra finches to the median sound of adult zebra finches, that act as a \"goal\" sound.\n\\begin{quote}\n\"For each syllable rendition, we calculated the proximity (Euclidean distance) to the median of the adult renditions of the syllable (age $>$ 90 days) in feature space (Fig. 2a,b).\"\n\\end{quote}\n\nThey contextualize that measurement by computing a \"relative quality\" that takes into account their current ability (e.g., are they getting closer or further compared to their previous 14 renditions).\n\\begin{quote}\n\"Because dopamine is hypothesized to encode the relative value of performance, we defined the 'relative quality' of a syllable as proximity to the adult version of the syllable relative to the mean of the previous 14 renditions (Methods).\"\n\\end{quote}\n\nThey define the \"closer\" measurements as the 10% of syllable renditions with the highest relative quality and the \"further\" as the lowest 10%.\n\\begin{quote}\n\"To test for online error responses, for each day we compared the dopamine activity associated with the 10% of syllable renditions with the highest relative quality with that of the 10% of renditions with the lowest relative quality (Fig. 2c–g).\"\n\\end{quote}\n\nNote that the data are measures of dopamine change, they use fibre photometry, changes in the fluorescence indicate dopamine changes in realtime. Their specific measurement considers the percent change in flourescence in 100-ms windows between 200 and 300 ms from the start of singing, averaged across development.\n\nFinally, the researchers note that they adjust the observations to correct for the increased dopamine for singing at all (whether it is close or far).\n\\begin{quote}\n\"As previously reported, the baseline level of dopamine in Area X is known to increase during singing; to isolate the effect of syllable quality from these singing-related dopamine increases, we subtracted the mean dopamine response across all renditions of a syllable on each day from the dopamine response for each rendition.\"\n\\end{quote}\n\nSo, the random variables we are working with are:\n\\begin{align*}\nX_{\\text{close}} &= \\text{average \\% change in fluorescence for the top 10\\% syllable renditions} \\\\\n&\\quad \\text{relative to distance from adult sound (corrected for singing)} \\\\[1ex]\nX_{\\text{far}} &= \\text{average \\% change in fluorescence for the bottom 10\\% syllable renditions} \\\\\n&\\quad \\text{relative to distance from adult sound (corrected for singing)}\n\\end{align*}\n\nThat is, the unit of measure is the syllable as measured on six birds, and the measurement is somewhat complicated.\n\n## Part a\nUsing the `pwr` package for \\texttt{R} [@pwr], conduct a power analysis. How many observations would the researchers need to detect a moderate-to-large effect ($d=0.65$) when using $\\alpha=0.05$ and default power (0.80) for a two-sided one sample $t$ test.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pwr)\npwr.t.test(d = 0.65, \n           power = 0.80, \n           alternative = \"two.sided\", \n           type=\"one.sample\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     One-sample t test power calculation \n\n              n = 20.58039\n              d = 0.65\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe researchers would need to collect at least 21 observations to detect a moderate-to-large effect.\n\n## Part b\nClick the link to go to the paper. Find the source data for Figure 2. Download the Excel file. Describe what you needed to do to collect the data for Figure 2(g). Note that you only need the `closer_vals` and `further_vals`. Ensure to `mutate()` the data to get a difference (e.g., `closer_vals - further_vals`).\n\n**Solution**\nOn nature.com I found firgure 2 which had a link to its source data. After downloading the excel file, I added a column name to each excel sheet respectively, the closer_vals and further_vals. I then downloaded each as csv files, and read them in to create a tibble of the values.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ncloser_data = read.csv(\"closer_vals.csv\")\nfurther_data = read.csv(\"further_vals.csv\")\n\ndat.vals = tibble(closer_vals = closer_data$closer_vals,\n              further_vals = further_data$further_vals) |>\n       mutate(difference = closer_vals - further_vals)\n```\n:::\n\n\n \\normalsize\n\n## Part c\nSummarize the data.\n\n* Summarize the further data. Do the data suggest that dopamine in the brains of young zebra finches decreases when they sing further away?\n* Summarize the closer data. Do the data suggest that dopamine in the brains of young zebra finches increases when they sing closer to their adult song?\n* Summarize the paired differences. Do the data suggest that there is a difference between dopamine in the brains of young zebra finches when they sing further away compared to closer to their adult song?\n* **Optional Challenge** Can you reproduce Figure 2(g)? Note that the you can use \\texttt{geom\\_errorbar()} to plot the range created by adding the mean $\\pm$ one standard deviation.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.vals |>\n  pivot_longer(cols = everything(), names_to = \"variable\", values_to = \"value\") |>\n  group_by(variable) |>\n  summarize(\n    mean = mean(value),\n    sd = sd(value),\n    median = median(value),\n    IQR = IQR(value),\n    skew = e1071::skewness(value)\n  ) |>\n  knitr::kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|variable     |   mean|    sd| median|   IQR|   skew|\n|:------------|------:|-----:|------:|-----:|------:|\n|closer_vals  |  0.179| 0.098|  0.144| 0.142|  0.264|\n|difference   |  0.391| 0.214|  0.353| 0.305|  0.666|\n|further_vals | -0.213| 0.134| -0.188| 0.191| -1.032|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\nThe mean of the further values is -.213, which being less than 0 suggests that dopamine in the brains of young zebra finches does decrease when they sing further away. Inversely, the mean of the closer values is .179, which being greater than 0, suggests that the dopamine in the brains of young zebra finches increases when they sing closer to their adult song. The difference between the two has a mean of .391, this is notably far from 0, meaning there is a difference in the dopamine of young zebra finches in the closer values compared to the further values.\n\n## Part d\nConduct the inferences they do in the paper. Make sure to report the results a little more comprehensively -- that is your parenthetical should look something like: ($t=23.99$, $p<0.0001$; $g=1.34$; 95% CI: 4.43, 4.60). Ensure to verify any conditions for use.\\\n**Note**: Your numbers will vary slightly because they reported two-sided test $p$-values instead of the specified one-sided tests. \n\n* \"The close responses differed significantly from 0 ($p=1.63 \\times 10^{-8}$).''\\\n**Note**: Use the appropriate one-sided test.\n* \"The far responses differed significantly from 0 ($p=5.17 \\times 10^{-8}$).''\\\n**Note**: Use the appropriate one-sided test.\n* \"The difference between populations was significant ($p=1.04 \\times10^{-8}$).''\\\n**Note**: Use the two-sided test.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effectsize)\n# Test 1. Closer vals greater than 0 (one-sided upper)\nt.test(dat.vals$closer_vals, mu = 0, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  dat.vals$closer_vals\nt = 9.1573, df = 24, p-value = 1.333e-09\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 0.1452511       Inf\nsample estimates:\nmean of x \n0.1786241 \n```\n\n\n:::\n\n```{.r .cell-code}\nhedges_g(dat.vals$closer_vals, mu = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHedges' g |       95% CI\n------------------------\n1.77      | [1.14, 2.39]\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test 2. Further vals less than 0 (one-sided lower)\nt.test(dat.vals$further_vals, mu = 0, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  dat.vals$further_vals\nt = -7.9245, df = 24, p-value = 1.866e-08\nalternative hypothesis: true mean is less than 0\n95 percent confidence interval:\n       -Inf -0.1668619\nsample estimates:\n mean of x \n-0.2128063 \n```\n\n\n:::\n\n```{.r .cell-code}\nhedges_g(dat.vals$further_vals, mu = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHedges' g |         95% CI\n--------------------------\n-1.53     | [-2.10, -0.95]\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test 3. Difference is different from 0 (two-sided)\nt.test(dat.vals$difference, mu = 0, alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  dat.vals$difference\nt = 9.1428, df = 24, p-value = 2.746e-09\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 0.3030683 0.4797923\nsample estimates:\nmean of x \n0.3914303 \n```\n\n\n:::\n\n```{.r .cell-code}\nhedges_g(dat.vals$difference, mu = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHedges' g |       95% CI\n------------------------\n1.77      | [1.14, 2.39]\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(dat.vals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nVerification: Because there is 25 rows of data and the power analysis told us we only need 21, rounding up, observations, the t-test condition is met.\n\nCloser vals: The close responses differed significantly from 0 (t=9.157, p=1.33e-09; g=1.77; 95% CI: 0.145, inf).\n\nFurther vals: The far responses differed significantly from 0 (t=−7.925, p=1.87e-08; g=−1.53g; 95% CI: -inf, −0.167).\n\nDifference: The difference between populations was significant (t=9.143, p=2.75e-09; g=1.77g; 95% CI: 0.303, 0.480).\n\n## Part e \n\nFor each hypothesis test in the previous question, plot the null $T$ \ndistribution and the observed $t$ statistic. Ensure to use \\texttt{geom\\_ribbon()} \nto highlight the rejection region and the $p$-value. Additionally, add the \nresampling distribution for $T$ to the chart to demonstrate any differences \nbetween the null distribution and the distribution suggested by the data.\n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='110%'}\n\n```{.r .cell-code}\nset.seed(7272)\n\nn = nrow(dat.vals)\ndf = n - 1\nalpha = 0.05\n\nt_close = 9.157\nt_far = -7.925\nt_diff = 9.143\n\ns_close = sd(dat.vals$closer_vals)\ns_far = sd(dat.vals$further_vals)\ns_diff = sd(dat.vals$difference)\n\n# Resampling\nts_close = rep(NA, 1000)\nfor(i in 1:1000){\n  curr.sample = sample(dat.vals$closer_vals, size = n, replace = TRUE)\n  ts_close[i] = (mean(curr.sample) - 0) / (s_close / sqrt(n))\n}\n\nts_far = rep(NA, 1000)\nfor(i in 1:1000){\n  curr.sample = sample(dat.vals$further_vals, size = n, replace = TRUE)\n  ts_far[i] = (mean(curr.sample) - 0) / (s_far / sqrt(n))\n}\n\nts_diff = rep(NA, 1000)\nfor(i in 1:1000){\n  curr.sample = sample(dat.vals$difference, size = n, replace = TRUE)\n  ts_diff[i] = (mean(curr.sample) - 0) / (s_diff / sqrt(n))\n}\n\nggdat1 = tibble(t = seq(-14, 14, length.out = 1000)) |>\n  mutate(pdf.h0 = dt(t, df = n - 1))\n\np1 = ggplot(ggdat1) +\n  geom_line(aes(x = t, y = pdf.h0)) +\n  stat_density(data = tibble(t = ts_close), aes(x = t), color = \"grey\", geom = \"line\") +\n  geom_hline(yintercept = 0) +\n  geom_ribbon(data = ggdat1 |> filter(t >= qt(1 - alpha, df)),\n              aes(x = t, ymin = 0, ymax = pdf.h0, fill = \"Rejection Region\"), alpha = 0.3) +\n  geom_ribbon(data = ggdat1 |> filter(t >= t_close),\n              aes(x = t, ymin = 0, ymax = pdf.h0, fill = \"P-Value\"), alpha = 0.3) +\n  geom_vline(xintercept = t_close, color = \"darkred\") +\n  theme_bw() +\n  labs(x = \"t\", y = \"Density\", title = \"Closer vals > 0 (one-sided upper)\", fill = \"\")\n\nggdat2 = tibble(t = seq(-14, 14, length.out = 1000)) |>\n  mutate(pdf.h0 = dt(t, df = n - 1))\n\np2 = ggplot(ggdat2) +\n  geom_line(aes(x = t, y = pdf.h0)) +\n  stat_density(data = tibble(t = ts_far), aes(x = t), color = \"grey\", geom = \"line\") +\n  geom_hline(yintercept = 0) +\n  geom_ribbon(data = ggdat2 |> filter(t <= qt(alpha, df)),\n              aes(x = t, ymin = 0, ymax = pdf.h0, fill = \"Rejection Region\"), alpha = 0.3) +\n  geom_ribbon(data = ggdat2 |> filter(t <= t_far),\n              aes(x = t, ymin = 0, ymax = pdf.h0, fill = \"P-Value\"), alpha = 0.3) +\n  geom_vline(xintercept = t_far, color = \"darkred\") +\n  theme_bw() +\n  labs(x = \"t\", y = \"Density\", title = \"Further vals < 0 (one-sided lower)\", fill = \"\")\n\nggdat3 = tibble(t = seq(-14, 14, length.out = 1000)) |>\n  mutate(pdf.h0 = dt(t, df = n - 1))\n\np3 = ggplot(ggdat3) +\n  geom_line(aes(x = t, y = pdf.h0)) +\n  stat_density(data = tibble(t = ts_diff), aes(x = t), color = \"grey\", geom = \"line\") +\n  geom_hline(yintercept = 0) +\n  geom_ribbon(data = ggdat3 |> filter(t >= qt(1 - alpha/2, df) | t <= qt(alpha/2, df)),\n              aes(x = t, ymin = 0, ymax = pdf.h0, fill = \"Rejection Region\"), alpha = 0.3) +\n  geom_ribbon(data = ggdat1 |> filter(t >= t_diff | t <= -t_diff),\n              aes(x = t, ymin = 0, ymax = pdf.h0, fill = \"P-Value\"), alpha = 0.3) +\n  geom_vline(xintercept = t_diff, color = \"darkred\") +\n  theme_bw() +\n  labs(x = \"t\", y = \"Density\", title = \"Difference ≠ 0 (two-sided)\", fill = \"\")\n\np1 / p2 / p3\n```\n\n::: {.cell-output-display}\n![Bootstrapping graphs](Lab13WriteUp_files/figure-pdf/Bootstrapping-1.pdf){fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n",
    "supporting": [
      "Lab13WriteUp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}